### ISSUE TITLE
requires a peer of react-native

### ISSUE THREAD

**Issue by ujjalghosh** [fast0490f/react-native-lock-task#1]
react-native run-android is working but when try to generate apk  file its error showing how ever i am using react native version  :  
react-native-cli: 2.0.1
react-native: 0.58.4

`react-native-lock-task@1.0.8` requires a peer of react-native@^0.41.2 but none is installed. You must install peer dependencies yourself.`

**Comment by manojkumawat003** [comment]
@ujjalghosh  I want to see no. of  password attempt in my console? How to do that?

**Comment by temaivanoff** [comment]
fix 1.0.10
