### ISSUE TITLE
assemble Release Fail

### ISSUE THREAD

**Issue by Couiljer** [fast0490f/react-native-lock-task#2]
Hi there, 

first thanks for this project, it's a pretty good job done. 😄 

I'm desperately trying to build a release version of a simple RN app with the lock task package. Everything works fine in dev mode. However, when compiling with `gradlew assembleRelease` It always turns into an error like following : 

` Build failed with an exception.
Execution failed for task ':react-native-lock-task:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  error: resource android:style/TextAppearance.Material.Widget.Button.Borderless.Colored not found.
  error: resource android:style/TextAppearance.Material.Widget.Button.Colored not found.
  /Users/jeremytwelve/app/apk/node_modules/react-native-lock-task/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:7: error: resource android:attr/colorError not found.
  /Users/jeremytwelve/app/apk/node_modules/react-native-lock-task/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:11: error: resource android:attr/colorError not found.
  /Users/jeremytwelve/app/apk/node_modules/react-native-lock-task/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:15: error: style attribute 'android:attr/keyboardNavigationCluster' not found.
  /Users/jeremytwelve/app/apk/node_modules/react-native-lock-task/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  /Users/jeremytwelve/app/apk/node_modules/react-native-lock-task/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  /Users/jeremytwelve/app/apk/node_modules/react-native-lock-task/android/build/intermediates/res/merged/release/values/values.xml:2711: error: resource android:attr/fontStyle not found.
  /Users/jeremytwelve/app/apk/node_modules/react-native-lock-task/android/build/intermediates/res/merged/release/values/values.xml:2712: error: resource android:attr/font not found.
  /Users/jeremytwelve/app/apk/node_modules/react-native-lock-task/android/build/intermediates/res/merged/release/values/values.xml:2713: error: resource android:attr/fontWeight not found.
  /Users/jeremytwelve/app/apk/node_modules/react-native-lock-task/android/build/intermediates/res/merged/release/values/values.xml:2714: error: resource android:attr/fontVariationSettings not found.
  /Users/jeremytwelve/app/apk/node_modules/react-native-lock-task/android/build/intermediates/res/merged/release/values/values.xml:2715: error: resource android:attr/ttcIndex not found.
  /Users/jeremytwelve/app/apk/node_modules/react-native-lock-task/android/build/intermediates/res/merged/release/values/values.xml:2796: error: resource android:attr/startX not found.
  /Users/jeremytwelve/app/apk/node_modules/react-native-lock-task/android/build/intermediates/res/merged/release/values/values.xml:2799: error: resource android:attr/startY not found.
  /Users/jeremytwelve/app/apk/node_modules/react-native-lock-task/android/build/intermediates/res/merged/release/values/values.xml:2802: error: resource android:attr/endX not found.
  /Users/jeremytwelve/app/apk/node_modules/react-native-lock-task/android/build/intermediates/res/merged/release/values/values.xml:2805: error: resource android:attr/endY not found.
  /Users/jeremytwelve/app/apk/node_modules/react-native-lock-task/android/build/intermediates/res/merged/release/values/values.xml:2813: error: resource android:attr/offset not found.
  error: failed linking references.
`
Does anyone have a solution for this ?

**Comment by akashsharma88** [comment]
I have the same problem and i fix it by updating `myproject/node_modules/react-native-lock-task/android/build.gradle`  with

```
buildscript {
    repositories {
         google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.0'
    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion 26
    buildToolsVersion "28.0.2"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
    }
    lintOptions {
        abortOnError false
    }
}
```

**Comment by Couiljer** [comment]
@akashsharma88 Thanks for your reply. 
I also fixed it by replacing targetSdkVersion and compileSdkVersion to 28 (in react-native-lock-task gradle file). Also removing the buildToolsVersion to avoid warning in android studio.
