### ISSUE TITLE
How to show status bar in lock task mode?

### ISSUE THREAD

**Issue by ltsharma** [fast0490f/react-native-lock-task#3]
I would like to show top status bar with this mode. how can i do that?

**Comment by ltsharma** [comment]
I have found a way by adding `setLockTaskFeatures (ComponentName, int flags)`
flag - LOCK_TASK_FEATURE_SYSTEM_INFO 
tried to add `myDevicePolicyManager.setLockTaskFeatures(mDPM, 1)` at line 52  in  `com/rnlocktask/RNLockTaskModule.java` (Im too bad in android)
but no success, can anyone help me to get it done?

**Comment by AppKidd** [comment]
@ltsharma Hi! The method `setLockTaskFeatures` is available from API 28. You need to change the compile version from 23 up to 28 in the build.gradle file inside react-native-lock-task. Once you've done that it should compile and show the status bar.

**Comment by ltsharma** [comment]
wow!!!!, it worked like a charm. Thank you very much @Appkidd. Appreciate your help.

**Comment by AppKidd** [comment]
@ltsharma You're very welcome!
