### ISSUE TITLE
Ability to create windows

### ISSUE THREAD

**Issue by HonzaJiran** [fast0490f/react-native-lock-task#7]
Hey,
is there any way to allow creating windows while being in lock-task mode?

My exact problem is that when I'm trying to connect to a bluetooth device/update app, android wants to render a dialog for PIN code/ actualization process, but this window is automatically blocked by lock-task mode.. :/

**Comment by temaivanoff** [comment]
HI
I'm not sure that this is possible, but you can definitely unlock a regular screen without a PIN code

**Comment by HonzaJiran** [comment]
Yeah..
Well, I fixed it quite badly but it's working. If anyone want to find a solution I did it like this:
When user should be prompted about pin code fe. I'll disable kiosk mode but also disable back button. The App is set to be "Home" app, so when user press the home/action button it will immediately send him back to the app 😄 

Edit: Other solution would be to use Android management API, but it's a huge process to get it working and pretty much unsuitable for smaller applications.
